### ISSUE TITLE
cannot unsqueeze empty tensor

### ISSUE THREAD

**Issue by PabloZheng** [PRIS-CV/AP-CNN_Pytorch-master#2]
excellent work!
I have some difficulties when I tried to use AP-CNN to train my customized dataset.
the error was raised in "line 452, def get_att_roi" , I wonder if this error has been encountered before and  what I can do to avoid this

**Comment by PabloZheng** [comment]
> excellent work!
> I have some difficulties when I tried to use AP-CNN to train my customized dataset.
> the error was raised in "line 452, def get_att_roi" , I wonder if this error has been encountered before and what I can do to avoid this

**Comment by joanbu2** [comment]
你好，我也遇到相同的错误，请问你有什么办法避免这种情况吗？
