### ISSUE TITLE
About baseline

### ISSUE THREAD

**Issue by WindVChen** [PRIS-CV/AP-CNN_Pytorch-master#3]
Hi,

I recently did some research on fine-grained classification, and I noticed that you achieve AP 84.1 on CUB_200_2011 with baseline Resnet50 in your paper. Are the super-parameters like 'lr', 'decay' and so on the same as that in your code when training on baseline? And should I change the last fc layer of Resnet50 into 200 num_classes when training?  I have been troubled by this for some time, as in my experiments, I can only get AP 82.9, while in some papers Resnet50 can go far to even 85.6 on CUB_200_2011.

My setting is as follows: 
1 lr=0.01, momentum =0.9, weight-decay=1e-4   
2 I use 10 epochs warm-up and then cosine decay like you
3 I change the 1000 num_classes into 200 in the last fc_layer
4 input is 448*448

Hope to get help from you. It did bother me for some time.

Thank you.

Kind regards.

**Comment by dingyf05** [comment]
Hi, we report baseline results given by [1], checkout the settings in our new project [CDB](https://github.com/PRIS-CV/DropChannelBlock_Pytorch_master) by setting --cdb=none to improve your baseline accuracy.

[1] Wang Y, et al.  Learning a discriminative filter bank within a cnn for fine-grained recognition//CVPR2018
