### ISSUE TITLE
关于可视化

### ISSUE THREAD

**Issue by MercuialC** [PRIS-CV/AP-CNN_Pytorch-master#4]
感谢您优秀的工作！
想请教一下对于论文中各层特征的黑白可视化图是用什么工具实现，能否提供可视化的思路或者代码。
非常感谢！

**Comment by dingyf05** [comment]
论文中我们对各层特征的spatial attention mask进行了可视化，将attention mask上各点的响应值由0～1映射到0~255转化为灰度图即可，[https://github.com/PRIS-CV/AP-CNN_Pytorch-master/blob/master/utils/utils.py](https://github.com/PRIS-CV/AP-CNN_Pytorch-master/blob/master/utils/utils.py)中已给出相关代码实现
