### ISSUE TITLE
关于对特征图进行上采样后，对原始特征利用Conv3x3的作用

### ISSUE THREAD

**Issue by mymuli** [PRIS-CV/AP-CNN_Pytorch-master#5]
你好！
我想问一下，在对特征图进行上采样后，对原始特征利用Conv3x3的作用是什么？
不应该是对上采样后的特征图进行3x3卷积操作呢？

https://github.com/PRIS-CV/AP-CNN_Pytorch-master/blob/00ddefee69ab35b8435b732bdf3bd7514a3e4545/model/resnet50.py#L211

**Comment by dingyf05** [comment]
参照FPN中的实现，在各层级的融合特征后接一个Conv3x3用于平滑上采样过程中带来的混叠效应(Finally, we append a 3×3 convolution on each merged map to generate the final feature map, which is to reduce the aliasing effect of upsampling[1])。

此处的P4_upsampled_x用于与P3层级的特征融合。

[1] Lin, Tsung-Yi, et al. "Feature pyramid networks for object detection." Proceedings of the IEEE conference on computer vision and pattern recognition. 2017.
