### ISSUE TITLE
您好，请问Dropblock的随机丢弃率怎么设置呢，我需要把更多的特征图层加进来

### ISSUE THREAD

**Issue by luoz66** [PRIS-CV/AP-CNN_Pytorch-master#6]
![image](https://user-images.githubusercontent.com/86155472/164977319-7e3e60e0-120a-4d38-9057-a792118cd648.png)

**Comment by dingyf05** [comment]
我们在Dropblock的随机丢弃率上没有进行过多的调参，可以尝试为浅层感受野较小的层级特征设置随机丢弃率，以及多个层级组合丢弃的形式
